@host=138.4.22.50
@port=80

### Start Components
POST http://{{host}}:{{port}}/serverControl/start
Content-Type: application/json

{}

### Stop Components
POST http://{{host}}:{{port}}/serverControl/stop
Content-Type: application/json

{}

### Stop Components
GET http://{{host}}:{{port}}/serverControl/status
Content-Type: application/json

### Stop Components
GET http://{{host}}:{{port}}/health
Content-Type: application/json

