# PATCH request to change ultrasound sensor distance
curl -X PATCH http://138.4.22.12:80/orion/ngsi-ld/v1/entities/urn:ngsi-ld:UltrasoundSensor:001/attrs \
-H 'Content-Type: application/json' \
-H 'Link: <http://context/datamodels.context-ngsi.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
-d '{"distance": {"type": "Property", "value": 20, "unitCode": "CMT"}}'
